Name: **Bibek Shrestha**\
ID: **2418629**

#Python Basics

##Exercise on Functions

###Task 1: Create a Python program that converts between different units of measurement.

In [1]:
def convert_units():
    """
    A program that converts between different units of measurement.
    Supports length (m/ft), weight (kg/lbs), and volume (L/gal).
    """
    print("Choose a conversion type:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    while True:
        conversion_type = input("Enter your choice (1/2/3): ")
        if conversion_type in ['1', '2', '3']:
            break
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")

    while True:
        try:
            value = float(input("Enter the value to convert: "))
            break
        except ValueError:
            print("Invalid input. Please enter a numeric value.")

    result = None
    unit_from = ''
    unit_to = ''

    if conversion_type == '1':  # Length conversion
        print("\nChoose length conversion:")
        print("a. Meters to Feet")
        print("b. Feet to Meters")
        while True:
            length_choice = input("Enter your choice (a/b): ").lower()
            if length_choice in ['a', 'b']:
                break
            else:
                print("Invalid choice. Please enter 'a' or 'b'.")
        if length_choice == 'a':
            result = value * 3.28084
            unit_from = 'meters'
            unit_to = 'feet'
        else:
            result = value / 3.28084
            unit_from = 'feet'
            unit_to = 'meters'
    elif conversion_type == '2':  # Weight conversion
        print("\nChoose weight conversion:")
        print("a. Kilograms to Pounds")
        print("b. Pounds to Kilograms")
        while True:
            weight_choice = input("Enter your choice (a/b): ").lower()
            if weight_choice in ['a', 'b']:
                break
            else:
                print("Invalid choice. Please enter 'a' or 'b'.")
        if weight_choice == 'a':
            result = value * 2.20462
            unit_from = 'kilograms'
            unit_to = 'pounds'
        else:
            result = value / 2.20462
            unit_from = 'pounds'
            unit_to = 'kilograms'
    elif conversion_type == '3':  # Volume conversion
        print("\nChoose volume conversion:")
        print("a. Liters to Gallons")
        print("b. Gallons to Liters")
        while True:
            volume_choice = input("Enter your choice (a/b): ").lower()
            if volume_choice in ['a', 'b']:
                break
            else:
                print("Invalid choice. Please enter 'a' or 'b'.")
        if volume_choice == 'a':
            result = value * 0.264172
            unit_from = 'liters'
            unit_to = 'gallons'
        else:
            result = value / 0.264172
            unit_from = 'gallons'
            unit_to = 'liters'

    if result is not None:
        print(f"\n{value:.2f} {unit_from} is equal to {result:.2f} {unit_to}.")
    else:
        print("An unexpected error occurred during conversion.")


convert_units()


Choose a conversion type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter your choice (1/2/3): 1
Enter the value to convert: 6

Choose length conversion:
a. Meters to Feet
b. Feet to Meters
Enter your choice (a/b): b

6.00 feet is equal to 1.83 meters.


###Task 2: Create a Python program that performs various mathematical operations on a list of numbers.

In [2]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of the numbers.

    Raises:
        ValueError: If the input list is empty.
    """
    if not numbers:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The maximum value in the list.

    Raises:
        ValueError: If the input list is empty.
    """
    if not numbers:
        raise ValueError("Cannot find maximum of an empty list.")
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Args:
        numbers (list): A list of numeric values.

    Returns:
        float: The minimum value in the list.

    Raises:
        ValueError: If the input list is empty.
    """
    if not numbers:
        raise ValueError("Cannot find minimum of an empty list.")
    return min(numbers)

def mathematical_operations_program():
    """
    A program that performs various mathematical operations on a list of numbers.
    Supports sum, average, maximum, and minimum.
    """
    print("Choose an operation:")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    while True:
        choice = input("Enter your choice (1/2/3/4): ")
        if choice in ['1', '2', '3', '4']:
            break
        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")

    while True:
        numbers_input = input("Enter a list of numbers separated by spaces: ")
        try:
            numbers = [float(x) for x in numbers_input.split()]
            if not numbers and choice != '0':
                print("The list of numbers cannot be empty for these operations. Please enter some numbers.")
                continue
            break
        except ValueError:
            print("Invalid input. Please enter numbers separated by spaces.")

    result = None
    operation_name = ""

    try:
        if choice == '1':
            result = calculate_sum(numbers)
            operation_name = "Sum"
        elif choice == '2':
            result = calculate_average(numbers)
            operation_name = "Average"
        elif choice == '3':
            result = find_maximum(numbers)
            operation_name = "Maximum"
        elif choice == '4':
            result = find_minimum(numbers)
            operation_name = "Minimum"

        if result is not None:
            print(f"The {operation_name} of {numbers_input} is: {result:.2f}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

mathematical_operations_program()

Choose an operation:
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Enter your choice (1/2/3/4): 1
Enter a list of numbers separated by spaces: 4 5 6 7 8 9
The Sum of 4 5 6 7 8 9 is: 39.00


##Exercise on List Manipulation

###Task 1:Write a Python function that extracts every other element from a list, starting from the first element.

In [4]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element.
    """
    return lst[::2]

first_list = [1, 2, 3, 4, 5, 6]
extracted_elements = extract_every_other(first_list)
print(f"Original list: {first_list}")
print(f"Every other element (starting from the first): {extracted_elements}")

second_list = ['a', 'b', 'c', 'd', 'e']
extracted_elements_2 = extract_every_other(second_list)
print(f"\nOriginal list: {second_list}")
print(f"Every other element (starting from the first): {extracted_elements_2}")

Original list: [1, 2, 3, 4, 5, 6]
Every other element (starting from the first): [1, 3, 5]

Original list: ['a', 'b', 'c', 'd', 'e']
Every other element (starting from the first): ['a', 'c', 'e']


###Task 2: Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

In [6]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, starting from a specified index
    and ending at another specified index (inclusive).

    Args:
        lst (list): The input list.
        start (int): The starting index (inclusive).
        end (int): The ending index (inclusive).

    Returns:
        list: The sublist from 'start' to 'end' (inclusive).
    """
    return lst[start : end + 1]

first_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
sublist = get_sublist(first_list, start_index, end_index)

print(f"Original list: {first_list}")
print(f"Sublist from index {start_index} to {end_index}: {sublist}")

second_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
start_index_2 = 1
end_index_2 = 5
sublist_2 = get_sublist(second_list, start_index_2, end_index_2)

print(f"\nOriginal list: {second_list}")
print(f"Sublist from index {start_index_2} to {end_index_2}: {sublist_2}")

Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]

Original list: ['a', 'b', 'c', 'd', 'e', 'f', 'g']
Sublist from index 1 to 5: ['b', 'c', 'd', 'e', 'f']


###Task 3: Write a Python function that reverses a list using slicing.

In [7]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list with elements in reverse order.
    """
    return lst[::-1]

first_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(first_list)

print(f"Original list: {first_list}")
print(f"Reversed list: {reversed_list}")

second_list = ['apple', 'banana', 'cherry']
reversed_second_list = reverse_list(second_list)

print(f"\nOriginal list: {second_list}")
print(f"Reversed list: {reversed_second_list}")

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]

Original list: ['apple', 'banana', 'cherry']
Reversed list: ['cherry', 'banana', 'apple']


###Task 4: Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

In [8]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list using slicing.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list without the first and last elements.
    """
    return lst[1:-1]


first_list = [1, 2, 3, 4, 5]
result_list = remove_first_last(first_list)

print(f"Original list: {first_list}")
print(f"List after removing first and last elements: {result_list}")

Original list: [1, 2, 3, 4, 5]
List after removing first and last elements: [2, 3, 4]


###Task 5: Write a Python function that extracts the first n elements from a list.

In [9]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list using slicing.

    Args:
        lst (list): The input list.
        n (int): Number of elements to extract.

    Returns:
        list: A new list containing the first n elements.
    """
    return lst[:n]


first_list = [1, 2, 3, 4, 5]
result_list = get_first_n(first_list, 3)

print(f"\nOriginal list: {first_list}")
print(f"First 3 elements: {result_list}")


Original list: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


###Task 6: Write a Python function that extracts the last n elements of a list using slicing.

In [10]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list using slicing.

    Args:
        lst (list): The input list.
        n (int): Number of elements to extract from the end.

    Returns:
        list: A new list containing the last n elements.
    """
    return lst[-n:]


first_list = [1, 2, 3, 4, 5]
result_list = get_last_n(first_list, 2)

print(f"\nOriginal list: {first_list}")
print(f"Last 2 elements: {result_list}")


Original list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


###Task 7: Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [12]:
def reverse_skip(lst):
    """
    Extracts elements in reverse order starting from the
    second-to-last element and skipping one element each time.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list with every second element in reverse order.
    """
    return lst[-2::-2]


first_list = [1, 2, 3, 4, 5, 6]
result_list = reverse_skip(first_list)

print(f"\nOriginal list: {first_list}")
print(f"Reverse skip list: {result_list}")


Original list: [1, 2, 3, 4, 5, 6]
Reverse skip list: [5, 3, 1]


##Exercise on Nested List

###Task 1: Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

In [13]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Args:
        lst (list): A nested list.

    Returns:
        list: A flattened list.
    """
    flat_list = []

    for item in lst:
        for element in item:
            flat_list.append(element)

    return flat_list


nested_list = [[1, 2], [3, 4], [5]]
flattened = flatten(nested_list)

print(f"Original list: {nested_list}")
print(f"Flattened list: {flattened}")

Original list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


###Task 2: Write a Python function that extracts a specific element from a nested list given its indices.

In [14]:
def access_nested_element(lst, indices):
    """
    Accesses an element from a nested list using indices.

    Args:
        lst (list): A nested list.
        indices (list): A list of indices.

    Returns:
        element: The element at the specified position.
    """
    element = lst

    for index in indices:
        element = element[index]

    return element


lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result = access_nested_element(lst, [1, 2])

print(f"\nNested list: {lst}")
print(f"Accessed element: {result}")


Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Accessed element: 6


###Task 3: Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [15]:
def sum_nested(lst):
    """
    Calculates the sum of all elements in a nested list.

    Args:
        lst (list): A nested list.

    Returns:
        int: Sum of all numbers.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item

    return total


nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print(f"\nNested list: {nested_list}")
print(f"Sum of elements: {result}")


Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of elements: 21


###Task 4: Write a Python function that removes all occurrences of a specific element from a nested list.

In [16]:
def remove_element(lst, elem):
    """
    Removes all occurrences of an element from a nested list.

    Args:
        lst (list): A nested list.
        elem (any): Element to remove.

    Returns:
        list: Modified list without the element.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)

    return result


lst = [[1, 2], [3, 2], [4, 5]]
result = remove_element(lst, 2)

print(f"\nOriginal list: {lst}")
print(f"List after removing 2: {result}")


Original list: [[1, 2], [3, 2], [4, 5]]
List after removing 2: [[1], [3], [4, 5]]


###Task 5: Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [17]:
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Args:
        lst (list): A nested list.

    Returns:
        int: Maximum element.
    """
    max_value = float('-inf')

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)

    return max_value


nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)

print(f"\nNested list: {nested_list}")
print(f"Maximum element: {result}")


Nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


###Task 6: Write a Python function that counts how many times a specific element appears in a nested list.

In [18]:
def count_occurrences(lst, elem):
    """
    Counts occurrences of an element in a nested list.

    Args:
        lst (list): A nested list.
        elem (any): Element to count.

    Returns:
        int: Number of occurrences.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count


lst = [[1, 2], [2, 3], [2, 4]]
result = count_occurrences(lst, 2)

print(f"\nNested list: {lst}")
print(f"Occurrences of 2: {result}")


Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


###Task 7: Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [19]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list regardless of depth.

    Args:
        lst (list): A deeply nested list.

    Returns:
        list: A completely flattened list.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result


nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print(f"\nOriginal list: {nested_list}")
print(f"Flattened list: {result}")


Original list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


###Task 8: Write a Python function that calculates the average of all elements in a nested list.

In [22]:
def average_nested(lst):
    """
    Calculates the average of elements in a nested list.

    Args:
        lst (list): A nested list.

    Returns:
        float: Average of all numbers.
    """
    total = 0
    count = 0

    def helper(sublist):
        nonlocal total, count
        for item in sublist:
            if isinstance(item, list):
                helper(item)
            else:
                total += item
                count += 1

    helper(lst)

    return total / count


nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print(f"\nNested list: {nested_list}")
print(f"Average value: {result}")


Nested list: [[1, 2], [3, 4], [5, 6]]
Average value: 3.5


#Numpy

##Basic Vector and Matrix Operation with Numpy.

###Problem - 1: Array Creation:

In [23]:
import numpy as np

#Initialize an empty array with size 2X2.
empty_array = np.empty((2,2))

print("Empty 2x2 Array:")
print(empty_array)

#Initialize an all one array with size 4X2.
ones_array = np.ones((4,2))

print("\n4x2 Ones Array:")
print(ones_array)

#Return a new array of given shape and type, filled with fill value.{Hint: np.full}
full_array = np.full((3,3), 7)

print("\nArray filled with 7:")
print(full_array)

#Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
original_array = np.array([[1,2,3],[4,5,6]])

zeros_like_array = np.zeros_like(original_array)

print("\nOriginal Array:")
print(original_array)

print("\nZeros like Original Array:")
print(zeros_like_array)

#Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_like_array = np.ones_like(original_array)

print("\nOnes like Original Array:")
print(ones_like_array)

#For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]

numpy_array = np.array(new_list)

print("\nConverted NumPy Array:")
print(numpy_array)


Empty 2x2 Array:
[[4.42203617e-315 0.00000000e+000]
 [4.94065646e-324             nan]]

4x2 Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Original Array:
[[1 2 3]
 [4 5 6]]

Zeros like Original Array:
[[0 0 0]
 [0 0 0]]

Ones like Original Array:
[[1 1 1]
 [1 1 1]]

Converted NumPy Array:
[1 2 3 4]


###Problem 2: Array Manipulation

In [24]:
import numpy as np

#Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
array_range = np.arange(10,50)

print("\nArray from 10 to 49:")
print(array_range)

#Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
matrix = np.arange(9).reshape(3,3)

print("\n3x3 Matrix (0–8):")
print(matrix)

#Create a 3X3 identity matrix.{Hint:np.eye()}
identity_matrix = np.eye(3)

print("\n3x3 Identity Matrix:")
print(identity_matrix)

#Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}
random_array = np.random.random(30)

mean_value = random_array.mean()

print("\nRandom Array:")
print(random_array)

print("Mean value:", mean_value)

#Create a 10X10 array with random values and find the minimum and maximum values.
random_matrix = np.random.random((10,10))

print("\n10x10 Random Matrix:")
print(random_matrix)

print("Minimum value:", random_matrix.min())
print("Maximum value:", random_matrix.max())

#Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10)

zero_array[4] = 1

print("\nZero Array with 5th element = 1:")
print(zero_array)

#Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1,2,0,0,4,0])

reversed_arr = arr[::-1]

print("\nOriginal Array:", arr)
print("Reversed Array:", reversed_arr)

#Create a 2d array with 1 on border and 0 inside.
border_array = np.ones((5,5))

border_array[1:-1,1:-1] = 0

print("\n2D Border Array:")
print(border_array)

#Create a 8X8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8,8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("\n8x8 Checkerboard Matrix:")
print(checkerboard)




Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix (0–8):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array:
[0.65887749 0.0851625  0.77434012 0.98669683 0.05336324 0.24234415
 0.52983279 0.82091897 0.03459286 0.86035104 0.73911168 0.42093952
 0.76244187 0.55810589 0.17355966 0.7526335  0.0127445  0.3771211
 0.44472179 0.50330563 0.70355864 0.78775979 0.93310415 0.59940962
 0.41646228 0.0152514  0.78590229 0.27187905 0.15662209 0.34751057]
Mean value: 0.4936208330455955

10x10 Random Matrix:
[[0.8075703  0.35663301 0.30413936 0.82526052 0.32862286 0.44235538
  0.02309672 0.54281146 0.80469313 0.16911482]
 [0.99051132 0.56094106 0.4391619  0.02305078 0.32482611 0.71057697
  0.23811181 0.57326771 0.94796125 0.75044758]
 [0.77319082 0.17876149 0.79276251 0.48880101 0.48353278 0.02769064
  0.78213271 0.47413331 0.51553606 0.45327101]
 

###Problem - 3: Array Operations:

In [25]:
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
# Complete all the task using numpy:

import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print("Array x:\n", x)
print("Array y:\n", y)
print("Vector v:", v)
print("Vector w:", w)

#Add the two array.
add_result = x + y

print("\nAddition of x and y:")
print(add_result)

#Subtract the two array.
sub_result = x - y

print("\nSubtraction of x and y:")
print(sub_result)

#Multiply the array with any integers of your choice.
multiply_result = x * 3

print("\nMultiplying x with 3:")
print(multiply_result)

#Find the square of each element of the array.
square_result = x ** 2

print("\nSquare of each element in x:")
print(square_result)

#Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw = np.dot(v, w)

print("\nDot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)

print("Dot product of x and v:", dot_xv)

dot_xy = np.dot(x, y)

print("Dot product of x and y:")
print(dot_xy)

#Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
concat_xy_row = np.concatenate((x,y), axis=0)

print("\nConcatenate x and y along rows:")
print(concat_xy_row)

concat_vw_col = np.vstack((v,w)).T

print("\nConcatenate v and w along column:")
print(concat_vw_col)

#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
    concat_xv = np.concatenate((x,v))
    print(concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:")
    print(e)
try:
    concat_xv = np.concatenate((x,v))
    print(concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:")
    print(e)


Array x:
 [[1 2]
 [3 5]]
Array y:
 [[5 6]
 [7 8]]
Vector v: [ 9 10]
Vector w: [11 12]

Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplying x with 3:
[[ 3  6]
 [ 9 15]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along column:
[[ 9 11]
 [10 12]]

Error while concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Error while concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


###Problem 4: Matrix Operations

In [27]:
# For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:

import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("\nMatrix A:\n", A)
print("\nMatrix B:\n", B)

#1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)

identity = np.dot(A, A_inv)

print("\nInverse of A:")
print(A_inv)

print("\nA * A_inverse:")
print(identity)

# 2. Prove AB ̸= BA.
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB:")
print(AB)

print("\nBA:")
print(BA)

# 3. Prove (AB)T = BTAT
left_side = np.transpose(np.dot(A,B))

right_side = np.dot(np.transpose(B), np.transpose(A))

print("\n(AB)^T:")
print(left_side)

print("\nB^T A^T:")
print(right_side)


Matrix A:
 [[3 4]
 [7 8]]

Matrix B:
 [[5 3]
 [2 1]]

Inverse of A:
[[-2.    1.  ]
 [ 1.75 -0.75]]

A * A_inverse:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

(AB)^T:
[[23 51]
 [13 29]]

B^T A^T:
[[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1\
x − y + 2z = −3\
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [28]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("\nSolution [x,y,z]:")
print(X)


Solution [x,y,z]:
[ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [29]:
solution = np.linalg.solve(A,B)

print("\nSolution using np.linalg.solve():")
print(solution)


Solution using np.linalg.solve():
[ 2.  1. -2.]


#Experiment: How Fast is Numpy?


###Element-wise Addition:

In [30]:
import numpy as np
import time

#Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000.
# Measure and Print the time taken for this operation.
size = 1_000_000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [a + b for a, b in zip(list1, list2)]

end = time.time()

print("Python List Addition Time:", end - start, "seconds")


#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()

result = arr1 + arr2

end = time.time()

print("NumPy Array Addition Time:", end - start, "seconds")


Python List Addition Time: 0.08102726936340332 seconds
NumPy Array Addition Time: 0.0201568603515625 seconds


###Element-wise Multiplication

In [31]:

# Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
# Measure and Print the time taken for this operation.
start = time.time()

result = [a * b for a, b in zip(list1, list2)]

end = time.time()

print("Python List Multiplication Time:", end - start, "seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.
start = time.time()

result = arr1 * arr2

end = time.time()

print("NumPy Array Multiplication Time:", end - start, "seconds")

Python List Multiplication Time: 0.09780693054199219 seconds
NumPy Array Multiplication Time: 0.022231578826904297 seconds


###Dot Product

In [32]:
# Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
# Print the time taken for this operation.
start = time.time()

dot_product = sum(a * b for a, b in zip(list1, list2))

end = time.time()

print("Python List Dot Product Time:", end - start, "seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.
start = time.time()

dot_product = np.dot(arr1, arr2)

end = time.time()

print("NumPy Dot Product Time:", end - start, "seconds")

Python List Dot Product Time: 0.11761093139648438 seconds
NumPy Dot Product Time: 0.0030870437622070312 seconds


###Matrix Multiplication

In [33]:
# Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
# sure and print the time taken for this operation.
size = 1000

A = [[1 for _ in range(size)] for _ in range(size)]
B = [[1 for _ in range(size)] for _ in range(size)]

start = time.time()

result = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Python List Matrix Multiplication Time:", end - start, "seconds")

# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
# Measure and print the time taken for this operation.
A = np.ones((1000,1000))
B = np.ones((1000,1000))

start = time.time()

result = np.dot(A,B)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start, "seconds")

Python List Matrix Multiplication Time: 327.4135310649872 seconds
NumPy Matrix Multiplication Time: 0.1050422191619873 seconds


#